=== powsybl/open-rao/data/crac/crac-io/crac-io-json/src/main/resources/schemas/crac/crac-v1.1.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema#",
  "$id": "https://www.powsybl.orgopen-rao-crac-schema=crac-v1.1.schema",
  "title": "CRAC",
  "description": "CRAC data for electric grid operation",
  "type": "object",
  "properties": {
    "type": {
      "const": "CRAC"
    },
    "version": {
      "const": "1.1"
    },
    "info": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "networkElementsNamePerId": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "contingencies": {
      "$ref": "resource:/schemas/common/contingency.json"
    },
    "flowCnecs": {
      "type": "array",
      "items": {
        "items": {
          "$ref": "resource:/schemas/flow-cnec/flow-cnec-v1.0.json"
        }
      }
    },
    "pstRangeActions": {
      "type": "array",
      "items": {
        "$ref": "resource:/schemas/pst-range-action/pst-range-action-v1.0.json"
      }
    },
    "hvdcRangeActions": {
      "type": "array",
      "items": {
        "$ref": "resource:/schemas/hvdc-range-action/hvdc-range-action-v1.0.json"
      }
    },
    "networkActions": {
      "type": "array",
      "items": {
        "$ref": "resource:/schemas/network-action/network-action-v1.1.json"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "type",
    "version",
    "id",
    "name",
    "contingencies",
    "flowCnecs",
    "pstRangeActions",
    "hvdcRangeActions",
    "networkActions"
  ]
}

=== powsybl/open-rao/tests/src/test/resources/files/crac/epic15/jsonCrac_ep15us17case12.json
{
  "type" : "CRAC",
  "version" : "1.1",
  "info" : "Generated by FARAO http://farao-community.github.io",
  "id" : "20161215_0430_2D4_CRAC_FR",
  "name" : "20161215_0430_2D4_CRAC_FR",
  "networkElementsNamePerId" : { },
  "contingencies" : [ ],
  "flowCnecs" : [ {
    "id" : "be1_be2_n - BBE1AA11->BBE2AA11 - preventive",
    "name" : "be1_be2_n",
    "networkElementId" : "BBE1AA11 BBE2AA11 1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -2000.0,
      "max" : 2000.0,
      "rule" : "onLeftSide"
    } ]
  }, {
    "id" : "be1_fr5_n - BBE1AA11->FFR5AA11 - preventive",
    "name" : "be1_fr5_n",
    "networkElementId" : "BBE1AA11 FFR5AA11 1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -2000.0,
      "max" : 2000.0,
      "rule" : "onLeftSide"
    } ]
  }, {
    "id" : "nl1_nl2_n - NNL1AA11->NNL2AA11 - preventive",
    "name" : "nl1_nl2_n",
    "networkElementId" : "NNL1AA11 NNL2AA11 1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "megawatt",
      "min" : -100.0,
      "max" : 100.0,
      "rule" : "onLeftSide"
    } ]
  }, {
    "id" : "be2_be5_n - BBE2AA11->BBE5AA11 - preventive",
    "name" : "be2_be5_n",
    "networkElementId" : "BBE2AA11 BBE5AA11 1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "megawatt",
      "min" : -10000.0,
      "max" : 10000.0,
      "rule" : "onLeftSide"
    } ]
  } ],
  "pstRangeActions" : [ ],
  "hvdcRangeActions" : [ {
    "id" : "PRA_HVDC",
    "name" : "PRA_HVDC",
    "operator" : "FR",
    "freeToUseUsageRules" : [ {
      "instant" : "preventive",
      "usageMethod" : "available"
    } ],
    "networkElementId" : "BBE5AA11 FFR3AA11 1",
    "ranges" : [ {
      "min" : -100.0,
      "max" : 100.0
    } ]
  } ],
  "networkActions" : [ ]
}

=== powsybl/open-rao/tests/src/test/resources/files/crac/epic15/jsonCrac_ep15us12-5case7.json
{
  "type" : "CRAC",
  "version" : "1.1",
  "info" : "Generated by FARAO http://farao-community.github.io",
  "id" : "20161215_0430_2D4_CRAC_FR",
  "name" : "20161215_0430_2D4_CRAC_FR",
  "networkElementsNamePerId" : { },
  "contingencies" : [ ],
  "flowCnecs" : [ {
    "id" : "de2_de3_n - DDE2AA11->DDE3AA11 - preventive",
    "name" : "de2_de3_n",
    "networkElementId" : "DDE2AA11 DDE3AA11 1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -72.0,
      "max" : 72.0,
      "rule" : "onLeftSide"
    } ]
  } ],
  "pstRangeActions" : [ ],
  "hvdcRangeActions" : [ {
    "id" : "PRA_HVDC",
    "name" : "PRA_HVDC",
    "operator" : "FR",
    "freeToUseUsageRules" : [ {
      "instant" : "preventive",
      "usageMethod" : "available"
    } ],
    "networkElementId" : "BBE2AA11 FFR3AA11 1",
    "ranges" : [ {
      "min" : -2000.0,
      "max" : 2000.0
    } ]
  } ],
  "networkActions" : [ ]
}

=== powsybl/open-rao/tests/src/test/resources/files/crac/epic15/crac_15_11_5_1bis.json
{
  "type" : "CRAC",
  "version" : "1.1",
  "info" : "Generated by FARAO http://farao-community.github.io",
  "id" : "20161215_0430_2D4_CRAC_FR",
  "name" : "20161215_0430_2D4_CRAC_FR",
  "networkElementsNamePerId" : { },
  "contingencies" : [ {
    "id" : "co1_fr2_de3",
    "networkElementsIds" : [ "FFR2AA11 DDE3AA11 1" ]
  } ],
  "flowCnecs" : [ {
    "id" : "de2_nl3 - DDE2AA11->NNL3AA11  - preventive",
    "name" : "de2_nl3 - prev",
    "networkElementId" : "DDE2AA11 NNL3AA11 1",
    "operator" : null,
    "instant" : "preventive",
    "contingencyId" : null,
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "megawatt",
      "min" : -2433.0,
      "max" : 2433.0,
      "rule" : "onLeftSide"
    } ]
  }, {
    "id" : "nl2_nl3_co1 - NNL2AA11->NNL3AA11  - co1_fr2_de3 - auto",
    "name" : "nl2_nl3_co1 - auto",
    "networkElementId" : "NNL2AA11 NNL3AA11 1",
    "operator" : null,
    "instant" : "auto",
    "contingencyId" : "co1_fr2_de3",
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "megawatt",
      "min" : -1463.0,
      "max" : 1463.0,
      "rule" : "onLeftSide"
    } ]
  }, {
    "id" : "de2_de3_co1 - DDE2AA11->DDE3AA11  - co1_fr2_de3 - auto",
    "name" : "de2_de3_co1 - auto",
    "networkElementId" : "DDE2AA11 DDE3AA11 1",
    "operator" : null,
    "instant" : "auto",
    "contingencyId" : "co1_fr2_de3",
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "megawatt",
      "min" : -2810.0,
      "max" : 2810.0,
      "rule" : "onLeftSide"
    } ]
  }, {
    "id" : "be1_be3_co1 - BBE1AA11->BBE3AA11  - co1_fr2_de3 - curative",
    "name" : "be1_be3_co1 - curative",
    "networkElementId" : "BBE1AA11 BBE3AA11 1",
    "operator" : null,
    "instant" : "curative",
    "contingencyId" : "co1_fr2_de3",
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "megawatt",
      "min" : -433.0,
      "max" : 433.0,
      "rule" : "onLeftSide"
    } ]
  }, {
    "id" : "de1_de3_co1 - DDE1AA11->DDE3AA11  - co1_fr2_de3 - curative",
    "name" : "de1_de3_co1 - curative",
    "networkElementId" : "DDE1AA11 DDE3AA11 1",
    "operator" : null,
    "instant" : "curative",
    "contingencyId" : "co1_fr2_de3",
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "megawatt",
      "min" : 1000.0,
      "rule" : "onLeftSide"
    } ]
  } ],
  "pstRangeActions" : [ {
    "id" : "pst_be",
    "name" : "pst_be",
    "operator" : "be",
    "freeToUseUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "networkElementId" : "BBE2AA11 BBE3AA11 1",
    "initialTap" : 0,
    "tapToAngleConversionMap" : {
      "-1" : -0.3896097993971608,
      "0" : 0.0,
      "-2" : -0.7792105912934298,
      "1" : 0.3896097993971608,
      "-3" : -1.1687933694373345,
      "2" : 0.7792105912934298,
      "-4" : -1.5583491300758083,
      "3" : 1.1687933694373345,
      "-5" : -1.9478688732023104,
      "4" : 1.5583491300758083,
      "-6" : -2.337343603803646,
      "5" : 1.9478688732023104,
      "-7" : -2.7267643331050597,
      "6" : 2.337343603803646,
      "-8" : -3.1161220798131644,
      "7" : 2.7267643331050597,
      "-9" : -3.505407871356285,
      "8" : 3.1161220798131644,
      "-10" : -3.894612745121778,
      "9" : 3.505407871356285,
      "-11" : -4.283727749689918,
      "10" : 3.894612745121778,
      "-12" : -4.672743946063913,
      "11" : 4.283727749689918,
      "-13" : -5.061652408895631,
      "12" : 4.672743946063913,
      "-14" : -5.4504442277066305,
      "13" : 5.061652408895631,
      "-15" : -5.839110508104064,
      "14" : 5.4504442277066305,
      "-16" : -6.2276423729910535,
      "15" : 5.839110508104064,
      "16" : 6.2276423729910535
    },
    "ranges" : [ {
      "min" : -16,
      "max" : 16,
      "rangeType" : "absolute"
    } ]
  } ],
  "hvdcRangeActions" : [ ],
  "networkActions" : [ {
    "id" : "open_de1_de2_open_nl2_be3 - prev",
    "name" : "open_de1_de2_open_nl2_be3 - prev",
    "operator" : "de",
    "freeToUseUsageRules" : [ {
      "instant" : "preventive",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "DDE1AA11 DDE2AA11 1",
      "actionType" : "open"
    }, {
      "networkElementId" : "NNL2AA11 BBE3AA11 2",
      "actionType" : "open"
    } ]
  }, {
    "id" : "close_fr2_de3 - co1 - auto",
    "name" : "close_fr2_de3 - co1 - auto",
    "operator" : "fr",
    "onFlowConstraintUsageRules" : [ {
      "instant" : "auto",
      "flowCnecId" : "nl2_nl3_co1 - NNL2AA11->NNL3AA11  - co1_fr2_de3 - auto"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR2AA11 DDE3AA11 3",
      "actionType" : "close"
    } ]
  }, {
    "id" : "open_de2_nl3 - co1 - auto",
    "name" : "open_de2_nl3 - co1 - auto",
    "operator" : "de",
    "onFlowConstraintUsageRules" : [ {
      "instant" : "auto",
      "flowCnecId" : "de2_de3_co1 - DDE2AA11->DDE3AA11  - co1_fr2_de3 - auto"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "DDE2AA11 NNL3AA11 2",
      "actionType" : "open"
    } ]
  } ]
}

=== powsybl/open-rao/tests/src/test/resources/files/crac/epic15/crac_15_11_5_3_3.json
{
  "type" : "CRAC",
  "version" : "1.1",
  "info" : "Generated by FARAO http://farao-community.github.io",
  "id" : "20161215_0430_2D4_CRAC_FR",
  "name" : "20161215_0430_2D4_CRAC_FR",
  "networkElementsNamePerId" : { },
  "contingencies" : [ {
    "id" : "co1_de1_de2",
    "networkElementsIds" : [ "DDE1AA11 DDE2AA11 1" ]
  } ],
  "flowCnecs" : [ {
    "id" : "de2_nl3 - DDE2AA11->NNL3AA11  - preventive",
    "name" : "de2_nl3 - prev",
    "networkElementId" : "DDE2AA11 NNL3AA11 1",
    "operator" : null,
    "instant" : "preventive",
    "contingencyId" : null,
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "megawatt",
      "min" : -2600.0,
      "max" : 2600.0,
      "rule" : "onLeftSide"
    } ]
  }, {
    "id" : "de2_nl3_co1 - DDE2AA11->NNL3AA11  - co1_de1_de2 - auto",
    "name" : "de2_nl3_co1 - auto",
    "networkElementId" : "DDE2AA11 NNL3AA11 1",
    "operator" : null,
    "instant" : "auto",
    "contingencyId" : "co1_de1_de2",
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "megawatt",
      "min" : -1700.0,
      "max" : 1700.0,
      "rule" : "onLeftSide"
    } ]
  }, {
    "id" : "de2_nl3_co1 - DDE2AA11->NNL3AA11  - co1_de1_de2 - curative",
    "name" : "de2_nl3_co1 - curative",
    "networkElementId" : "DDE2AA11 NNL3AA11 1",
    "operator" : null,
    "instant" : "curative",
    "contingencyId" : "co1_de1_de2",
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "megawatt",
      "min" : -100.0,
      "max" : 100.0,
      "rule" : "onLeftSide"
    } ]
  }, {
    "id" : "be1_be3_co1 - BBE1AA11->BBE3AA11  - co1_de1_de2 - curative",
    "name" : "be1_be3_co1 - curative",
    "networkElementId" : "BBE1AA11 BBE3AA11 1",
    "operator" : null,
    "instant" : "curative",
    "contingencyId" : "co1_de1_de2",
    "optimized" : true,
    "monitored" : false,
    "frm" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "megawatt",
      "min" : -600.0,
      "max" : 600.0,
      "rule" : "onLeftSide"
    } ]
  } ],
  "pstRangeActions" : [ {
    "id" : "pst_be",
    "name" : "pst_be",
    "operator" : "be",
    "onStateUsageRules" : [ {
      "instant" : "curative",
      "contingencyId" : "co1_de1_de2",
      "usageMethod" : "available"
    } ],
    "networkElementId" : "BBE2AA11 BBE3AA11 1",
    "initialTap" : 0,
    "tapToAngleConversionMap" : {
      "-1" : -0.3896097993971608,
      "0" : 0.0,
      "-2" : -0.7792105912934298,
      "1" : 0.3896097993971608,
      "-3" : -1.1687933694373345,
      "2" : 0.7792105912934298,
      "-4" : -1.5583491300758083,
      "3" : 1.1687933694373345,
      "-5" : -1.9478688732023104,
      "4" : 1.5583491300758083,
      "-6" : -2.337343603803646,
      "5" : 1.9478688732023104,
      "-7" : -2.7267643331050597,
      "6" : 2.337343603803646,
      "-8" : -3.1161220798131644,
      "7" : 2.7267643331050597,
      "-9" : -3.505407871356285,
      "8" : 3.1161220798131644,
      "-10" : -3.894612745121778,
      "9" : 3.505407871356285,
      "-11" : -4.283727749689918,
      "10" : 3.894612745121778,
      "-12" : -4.672743946063913,
      "11" : 4.283727749689918,
      "-13" : -5.061652408895631,
      "12" : 4.672743946063913,
      "-14" : -5.4504442277066305,
      "13" : 5.061652408895631,
      "-15" : -5.839110508104064,
      "14" : 5.4504442277066305,
      "-16" : -6.2276423729910535,
      "15" : 5.839110508104064,
      "16" : 6.2276423729910535
    },
    "ranges" : [ {
      "min" : -16,
      "max" : 16,
      "rangeType" : "absolute"
    } ]
  } ],
  "hvdcRangeActions" : [ ],
  "networkActions" : [ {
    "id" : "open_nl1_nl3 - co1 - auto",
    "name" : "open_nl2_nl3 - co1 - auto",
    "operator" : "fr",
    "onFlowConstraintUsageRules" : [ {
      "instant" : "auto",
      "flowCnecId" : "de2_nl3_co1 - DDE2AA11->NNL3AA11  - co1_de1_de2 - auto"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "NNL1AA11 NNL3AA11 1",
      "actionType" : "open"
    } ]
  }, {
    "id" : "open_fr2_de3 - co1 - curative",
    "name" : "open_fr2_de3 - co1 - curative",
    "operator" : "fr",
    "onStateUsageRules" : [ {
      "instant" : "curative",
      "contingencyId" : "co1_de1_de2",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR2AA11 DDE3AA11 1",
      "actionType" : "open"
    } ]
  } ]
}
