=== powsybl/open-rao/data/crac-creation/crac-creator-fb-constraint/src/main/resources/xsd/flowbasedconstraintdocument-18.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="flowbased" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ecc="etso-core-cmpts.xsd" xmlns:fb="flowbased">
	<import namespace="etso-core-cmpts.xsd" schemaLocation="etso-core-cmpts.xsd"/>
	<element name="FlowBasedConstraintDocument">
		<complexType>
			<sequence>
				<element name="DocumentIdentification" type="ecc:IdentificationType"/>
				<element name="DocumentVersion" type="ecc:VersionType"/>
				<element name="DocumentType" type="ecc:MessageType"/>
				<element name="ProcessType" type="ecc:ProcessType"/>
				<element name="SenderIdentification" type="ecc:PartyType"/>
				<element name="SenderRole" type="ecc:RoleType"/>
				<element name="ReceiverIdentification" type="ecc:PartyType"/>
				<element name="ReceiverRole" type="ecc:RoleType"/>
				<element name="CreationDateTime" type="ecc:MessageDateTimeType"/>
				<element name="ConstraintTimeInterval" type="ecc:TimeIntervalType"/>
				<element name="Domain" type="ecc:AreaType"/>
				<element minOccurs="0" name="criticalBranches" type="fb:CriticalBranchesType"/>
				<element minOccurs="0" name="complexVariants" type="fb:complexVariantsType"/>
			</sequence>
			<attribute name="DtdVersion" type="string" use="required"/>
			<attribute name="DtdRelease" type="string" use="required"/>
		</complexType>
	</element>
	<complexType name="CriticalBranchesType">
		<sequence>
			<element maxOccurs="unbounded" minOccurs="0" name="criticalBranch" type="fb:criticalBranchType"/>
		</sequence>
	</complexType>
	<complexType name="complexVariantsType">
		<sequence>
			<element maxOccurs="unbounded" minOccurs="0" name="complexVariant" type="fb:independant_complexVariant"/>
		</sequence>
	</complexType>
	<simpleType name="nonEmptyString">
		<restriction base="string">
			<minLength value="1"/>
		</restriction>
	</simpleType>
	<simpleType name="idString">
		<restriction base="string">
			<minLength value="1"/>
			<maxLength value="100"/>
		</restriction>
	</simpleType>
	<simpleType name="tso_code">
		<restriction base="string">
			<pattern value="[A-Z0-9]{2}"/>
		</restriction>
	</simpleType>
	<simpleType name="perUnitUnlimited">
		<restriction base="decimal">
			<minInclusive value="0"/>
		</restriction>
	</simpleType>
	<simpleType name="nodeType">
		<restriction base="string">
			<pattern value=".{6}\d(\p{L}|\d| )?"/>
		</restriction>
	</simpleType>
	<simpleType name="Date">
		<restriction base="string">
			<pattern value="\d{4}/(0[1-9]|1[012])/(0[1-9]|[12][0-9]|3[01])"/>
		</restriction>
	</simpleType>
	<simpleType name="DateTime">
		<restriction base="string">
			<pattern value="\d{4}/(0[1-9]|1[012])/(0[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):([0-5][0-9])"/>
		</restriction>
	</simpleType>
	<simpleType name="minRAMfactor_Type">
		<restriction base="decimal">
			<minInclusive value="0"/>
			<maxInclusive value="100"/>
		</restriction>
	</simpleType>
	<complexType name="outageType">
		<sequence>
			<element maxOccurs="unbounded" minOccurs="0" name="branch">
				<complexType>
					<attribute name="from" type="fb:nodeType" use="required"/>
					<attribute name="to" type="fb:nodeType" use="required"/>
					<attribute name="order" use="optional">
						<simpleType>
							<restriction base="string">
								<pattern value="[1-9]|[A-Z]"/>
							</restriction>
						</simpleType>
					</attribute>
					<attribute name="elementName" type="fb:nonEmptyString" use="optional"/>
					<attribute name="eic" type="fb:nonEmptyString" use="required"/>
				</complexType>
				<key name="outageBranch__order_OR_elementName">
					<selector xpath="."/>
					<field xpath="@order|@elementName"/>
				</key>
			</element>
			<element maxOccurs="unbounded" minOccurs="0" name="hvdcVH">
				<complexType>
					<attribute name="from" type="fb:nodeType" use="required"/>
					<attribute name="to" type="fb:nodeType" use="required"/>
					<attribute name="eic" type="fb:nonEmptyString" use="required"/>
				</complexType>
			</element>
		</sequence>
		<attribute name="name" type="fb:nonEmptyString" use="optional"/>
		<attribute name="id" type="fb:idString" use="required"/>
		<attribute name="location" type="fb:nonEmptyString" use="optional"/>
	</complexType>
	<complexType name="criticalBranchType">
		<sequence>
			<element name="timeInterval" type="ecc:TimeIntervalType"/>
			<element minOccurs="1" name="branch">
				<complexType>
					<attribute name="from" type="fb:nodeType" use="required"/>
					<attribute name="to" type="fb:nodeType" use="required"/>
					<attribute name="order" use="optional">
						<simpleType>
							<restriction base="string">
								<pattern value="[1-9]|[A-Z]"/>
							</restriction>
						</simpleType>
					</attribute>
					<attribute name="elementName" type="fb:nonEmptyString" use="optional"/>
					<attribute name="name" type="fb:nonEmptyString" use="required"/>
					<attribute name="eic" type="fb:nonEmptyString" use="required"/>
				</complexType>
				<key name="criticalBranch__order_OR_elementName">
					<selector xpath="."/>
					<field xpath="@order|@elementName"/>
				</key>
			</element>
			<choice minOccurs="0">
				<element name="imaxA" type="float"/>
				<element name="imaxFactor" type="fb:perUnitUnlimited"/>
			</choice>
			<element name="imaxType" minOccurs="1">
				<simpleType>
					<restriction base="string">
						<enumeration value="FIXED"/>
						<enumeration value="SEASONAL"/>
						<enumeration value="DYNAMIC"/>
					</restriction>
				</simpleType>
			</element>
			<choice minOccurs="0">
				<element name="permanentImaxA" type="float"/>
				<element name="permanentImaxFactor" type="fb:perUnitUnlimited"/>
			</choice>
			<choice minOccurs="0">
				<element name="temporaryImaxA" type="float"/>
				<element name="temporaryImaxFactor" type="fb:perUnitUnlimited"/>
			</choice>
			<element name="frmMw" type="float"/>
			<element minOccurs="0" name="CVA" type="float"/>
			<element minOccurs="0" name="CVAJustification" type="fb:nonEmptyString"/>
			<element minOccurs="0" name="IVA" type="float"/>
			<element minOccurs="0" name="IVAJustification" type="fb:nonEmptyString"/>
			<element minOccurs="1" name="minRAMfactor" type="fb:minRAMfactor_Type"/>
			<element minOccurs="1" name="CNEC" type="boolean"/>
			<element minOccurs="1" name="MNEC" type="boolean"/>
			<element minOccurs="0" name="NECTypeJustification" type="fb:nonEmptyString"/>
			<element maxOccurs="1" minOccurs="1" name="direction">
				<simpleType>
					<restriction base="string">
						<enumeration value="DIRECT"/>
						<enumeration value="OPPOSITE"/>
					</restriction>
				</simpleType>
			</element>
			<element maxOccurs="1" minOccurs="1" name="tsoOrigin" type="fb:tso_code"/>
			<element minOccurs="0" name="outage" type="fb:outageType"/>
			<element minOccurs="0" name="complexVariantId" type="string"/>
		</sequence>
		<attribute name="id" type="fb:idString" use="required"/>
		<attribute name="originalId" type="fb:idString" use="optional"/>
	</complexType>
	<complexType name="independant_complexVariant">
		<sequence>
			<element name="timeInterval" type="ecc:TimeIntervalType"/>
			<element name="tsoOrigin" type="fb:tso_code" maxOccurs="1" minOccurs="1"/>
			<element maxOccurs="unbounded" minOccurs="1" name="actionsSet" type="fb:actionsSetType"/>
		</sequence>
		<attribute name="id" type="fb:idString" use="required"/>
		<attribute name="name" type="fb:nonEmptyString"/>
	</complexType>
	<complexType name="actionsSetType">
		<sequence>
			<element minOccurs="1" name="preventive" type="boolean"/>
			<element minOccurs="1" name="curative" type="boolean"/>
			<element minOccurs="0" name="enforced" type="boolean"/>
			<element minOccurs="0" name="afterCOList">
				<complexType>
					<sequence>
						<element maxOccurs="unbounded" minOccurs="1" name="afterCOId" type="fb:idString" />
					</sequence>
				</complexType>
			</element>
			<element maxOccurs="unbounded" name="action" type="fb:actionType"/>
		</sequence>
		<attribute name="name" type="fb:nonEmptyString" use="optional"/>
	</complexType>
	<complexType mixed="true" name="actionType">
		<all>
			<element minOccurs="1" name="branch">
				<complexType>
					<attribute name="from" type="fb:nodeType" use="required"/>
					<attribute name="to" type="fb:nodeType" use="required"/>
					<attribute name="order" use="optional">
						<simpleType>
							<restriction base="string">
								<pattern value="[1-9]|[A-Z]"/>
							</restriction>
						</simpleType>
					</attribute>
					<attribute name="elementName" type="fb:nonEmptyString" use="optional"/>
				</complexType>
				<key name="actionBranch__order_OR_elementName">
					<selector xpath="."/>
					<field xpath="@order|@elementName"/>
				</key>
			</element>
			<element minOccurs="0" name="value" type="fb:nonEmptyString"/>
			<element minOccurs="0" name="range" type="fb:rangeType"/>
			<element minOccurs="0" name="relativeRange" type="fb:rangeType"/>
			<element minOccurs="0" name="PSTGroupId" type="fb:nonEmptyString"/>
		</all>
		<attribute name="type" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="STATUS"/>
					<enumeration value="PSTTAP"/>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
	<complexType name="rangeType">
		<sequence>
			<element name="min" minOccurs="1" type="integer"/>
			<element name="max" minOccurs="1" type="integer"/>
		</sequence>
	</complexType>
</schema>

=== powsybl/open-rao/tests/src/test/resources/files/crac/epic12/MergedCB_12_2_1.xml
<?xml version='1.0' encoding='UTF-8'?>
<FlowBasedConstraintDocument DtdRelease="4" DtdVersion="0" xmlns="flowbased" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flowbasedconstraintdocument-18.xsd">
  <DocumentIdentification v="17XTSO-CS------W-20190108-F301v1"/>
  <DocumentVersion v="1"/>
  <DocumentType v="B06"/>
  <ProcessType v="A01"/>
  <SenderIdentification codingScheme="A01" v="17XTSO-CS------W"/>
  <SenderRole v="A36"/>
  <ReceiverIdentification codingScheme="A01" v="22XCORESO------S"/>
  <ReceiverRole v="A44"/>
  <CreationDateTime v="2019-08-15T14:07:28Z"/>
  <ConstraintTimeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
  <Domain codingScheme="A01" v="10Y1001C--00059P"/>
  <criticalBranches>
    <criticalBranch id="fr1_fr2_n_dir">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="FR1-FR2" from="FFR1AA1" to="FFR2AA1" order="1" eic="1234567890123451"/>
      <imaxA>1443</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="fr1_fr2_n_opp">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="FR1-FR2" from="FFR1AA1" to="FFR2AA1" order="1" eic="1234567890123451"/>
      <imaxA>1443</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>OPPOSITE</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="fr2_de3_n_dir">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="FR2-DE3" from="FFR2AA1" to="DDE3AA1" order="1" eic="1234567890123451"/>
      <imaxA>7215</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="fr2_de3_n_opp">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="FR2-DE3" from="FFR2AA1" to="DDE3AA1" order="1" eic="1234567890123451"/>
      <imaxA>7215</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>OPPOSITE</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="de2_nl3_n_dir">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="DE2-NL3" from="DDE2AA1" to="NNL3AA1" order="1" eic="1234567890123451"/>
      <imaxA>7215</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="de2_nl3_n_opp">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="DE2-NL3" from="DDE2AA1" to="NNL3AA1" order="1" eic="1234567890123451"/>
      <imaxA>7215</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>OPPOSITE</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="nl2_be3_n_dir">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="NL2-BE3" from="NNL2AA1" to="BBE3AA1" order="1" eic="1234567890123451"/>
      <imaxA>7215</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="nl2_be3_n_opp">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="NL2-BE3" from="NNL2AA1" to="BBE3AA1" order="1" eic="1234567890123451"/>
      <imaxA>7215</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>OPPOSITE</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="be2_fr3_n_dir">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="BE2-FR3" from="BBE2AA1" to="FFR3AA1" order="1" eic="1234567890123451"/>
      <imaxA>7215</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="be2_fr3_n_opp">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="BE2-FR3" from="BBE2AA1" to="FFR3AA1" order="1" eic="1234567890123451"/>
      <imaxA>7215</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>OPPOSITE</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="nl2_nl3_n_dir">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="NL2-NL3" from="NNL2AA1" to="NNL3AA1" order="1" eic="1234567890123451"/>
      <imaxA>7215</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>false</CNEC>
      <MNEC>true</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="nl2_nl3_n_opp">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="NL2-NL3" from="NNL2AA1" to="NNL3AA1" order="1" eic="1234567890123451"/>
      <imaxA>7215</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>false</CNEC>
      <MNEC>true</MNEC>
      <direction>OPPOSITE</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="nl1_nl3_n_dir">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="NL1-NL3" from="NNL1AA1" to="NNL3AA1" order="1" eic="1234567890123451"/>
      <imaxA>7215</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="nl1_nl3_n_opp">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="NL1-NL3" from="NNL1AA1" to="NNL3AA1" order="1" eic="1234567890123451"/>
      <imaxA>7215</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>OPPOSITE</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
  </criticalBranches>
  <complexVariants>
    <complexVariant id="PRA_PST_BE" name="PRA_PST_BE">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <tsoOrigin>BE</tsoOrigin>
      <actionsSet name="PRA_PST_BE">
        <preventive>true</preventive>
        <curative>false</curative>
        <enforced>false</enforced>
        <action type="PSTTAP">
          <branch order="1" from="BBE2AA1" to="BBE3AA1"/>
          <range>
            <min>-16</min>
            <max>16</max>
          </range>
        </action>
      </actionsSet>
    </complexVariant>
  </complexVariants>
</FlowBasedConstraintDocument>

=== powsybl/open-rao/data/crac-creation/crac-creator-fb-constraint/src/test/resources/merged_cb/thresholds_test.xml
<?xml version='1.0' encoding='UTF-8'?>
<FlowBasedConstraintDocument DtdRelease="4" DtdVersion="0" xmlns="flowbased" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flowbasedconstraintdocument-18.xsd">
  <DocumentIdentification v="17XTSO-CS------W-20190108-F301v1"/>
  <DocumentVersion v="1"/>
  <DocumentType v="B06"/>
  <ProcessType v="A01"/>
  <SenderIdentification codingScheme="A01" v="17XTSO-CS------W"/>
  <SenderRole v="A36"/>
  <ReceiverIdentification codingScheme="A01" v="22XCORESO------S"/>
  <ReceiverRole v="A44"/>
  <CreationDateTime v="2019-08-15T14:07:28Z"/>
  <ConstraintTimeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
  <Domain codingScheme="A01" v="10Y1001C--00059P"/>
  <criticalBranches>
    <criticalBranch id="CBCO_000001">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch eic="1234567890123451" from="DDE2AA1" name="XXX" order="1" to="DDE3AA1"/>
      <imaxType>SEASONAL</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>70</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>HU</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="CBCO_000002">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch eic="1234567890123452" from="NNL1AA11" name="XXX" order="1" to="NNL3AA11"/>
      <imaxA>200</imaxA>
      <imaxType>SEASONAL</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>70</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>HU</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="CBCO_000003">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch eic="1234567890123453" from="FFR2AA11" name="XXX" order="1" to="FFR3AA11"/>
      <imaxFactor>0.8</imaxFactor>
      <imaxType>SEASONAL</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>70</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>HU</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="CBCO_000004">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch eic="1234567890123453" from="FFR1AA11" name="XXX" order="7" to="FFR2AA11"/>
      <imaxType>SEASONAL</imaxType>
      <permanentImaxA>300</permanentImaxA>
      <frmMw>0</frmMw>
      <minRAMfactor>70</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>HU</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="CBCO_000005">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch eic="1234567890123453" from="NNL1AA11" name="XXX" order="1" to="NNL2AA11"/>
      <imaxType>SEASONAL</imaxType>
      <permanentImaxFactor>1.2</permanentImaxFactor>
      <frmMw>0</frmMw>
      <minRAMfactor>70</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>HU</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="CBCO_000006">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch eic="1234567890123453" from="BBE1AA11" name="XXX" order="5" to="BBE3AA11"/>
      <imaxType>SEASONAL</imaxType>
      <temporaryImaxA>200</temporaryImaxA>
      <frmMw>0</frmMw>
      <minRAMfactor>70</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>HU</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="CBCO_000007">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch eic="1234567890123453" from="DDE1AA11" name="XXX" order="1" to="DDE2AA11"/>
      <imaxType>SEASONAL</imaxType>
      <temporaryImaxFactor>0.8</temporaryImaxFactor>
      <frmMw>0</frmMw>
      <minRAMfactor>70</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>HU</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="CBCO_000008">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch eic="1234567890123453" from="BBE1AA11" name="XXX" order="5" to="BBE2AA11"/>
      <imaxA>200</imaxA>
      <imaxType>SEASONAL</imaxType>
      <permanentImaxA>300</permanentImaxA>
      <temporaryImaxA>100</temporaryImaxA>
      <frmMw>0</frmMw>
      <minRAMfactor>70</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>HU</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="CBCO_000009">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch eic="1234567890123453" from="DDE1AA11" name="XXX" order="1" to="DDE3AA11"/>
      <imaxFactor>1.2</imaxFactor>
      <imaxType>SEASONAL</imaxType>
      <permanentImaxFactor>0.8</permanentImaxFactor>
      <temporaryImaxFactor>0.6</temporaryImaxFactor>
      <frmMw>0</frmMw>
      <minRAMfactor>70</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>HU</tsoOrigin>
    </criticalBranch>
  </criticalBranches>
</FlowBasedConstraintDocument>

=== powsybl/open-rao/tests/src/test/resources/files/crac/epic12/MergedCB_12_6_2.xml
<?xml version='1.0' encoding='UTF-8'?>
<FlowBasedConstraintDocument DtdRelease="4" DtdVersion="0" xmlns="flowbased" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flowbasedconstraintdocument-18.xsd">
  <DocumentIdentification v="17XTSO-CS------W-20190108-F301v1"/>
  <DocumentVersion v="1"/>
  <DocumentType v="B06"/>
  <ProcessType v="A01"/>
  <SenderIdentification codingScheme="A01" v="17XTSO-CS------W"/>
  <SenderRole v="A36"/>
  <ReceiverIdentification codingScheme="A01" v="22XCORESO------S"/>
  <ReceiverRole v="A44"/>
  <CreationDateTime v="2019-08-15T14:07:28Z"/>
  <ConstraintTimeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
  <Domain codingScheme="A01" v="10Y1001C--00059P"/>
  <criticalBranches>
    <criticalBranch id="be1_fr5_n_dir">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="BE1-FR5" from="BBE1AA1" to="FFR5AA1" order="1" eic="1234567890123451"/>
      <imaxA>1500</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="be1_fr5_n_oppo">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="BE1-FR5" from="BBE1AA1" to="FFR5AA1" order="1" eic="1234567890123451"/>
      <imaxA>1500</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>OPPOSITE</direction>
      <tsoOrigin>FR</tsoOrigin>
    </criticalBranch>
    <criticalBranch id="fr3_fr5_co1_dir">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="FR3-FR5" from="FFR3AA1" to="FFR5AA1" order="1" eic="1234567890123451"/>
      <imaxA>1000</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>DIRECT</direction>
      <tsoOrigin>FR</tsoOrigin>
      <outage id="Contingency FR2 FR3" location="FR-FR" name="Contingency FR2 FR3">
        <branch eic="1234567890123450" from="FFR2AA1" order="1" to="FFR3AA1"/>
      </outage>
    </criticalBranch>
    <criticalBranch id="fr3_fr5_co1_oppo">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <branch name="FR3-FR5" from="FFR3AA1" to="FFR5AA1" order="1" eic="1234567890123451"/>
      <imaxA>1000</imaxA>
      <imaxType>FIXED</imaxType>
      <frmMw>0</frmMw>
      <minRAMfactor>100</minRAMfactor>
      <CNEC>true</CNEC>
      <MNEC>false</MNEC>
      <direction>OPPOSITE</direction>
      <tsoOrigin>FR</tsoOrigin>
      <outage id="Contingency FR2 FR3" location="FR-FR" name="Contingency FR2 FR3">
        <branch eic="1234567890123450" from="FFR2AA1" order="1" to="FFR3AA1"/>
      </outage>
    </criticalBranch>
  </criticalBranches>
  <complexVariants>
    <complexVariant id="PRA_PST_BE" name="PRA_PST_BE">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <tsoOrigin>BE</tsoOrigin>
      <actionsSet name="PRA_PST_BE">
        <preventive>true</preventive>
        <curative>false</curative>
        <enforced>false</enforced>
        <action type="PSTTAP">
          <branch order="1" from="BBE2AA1" to="BBE3AA1"/>
          <range>
            <min>-16</min>
            <max>16</max>
          </range>
        </action>
      </actionsSet>
    </complexVariant>
    <complexVariant id="PRA_PST_FR" name="PRA_PST_FR">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <tsoOrigin>FR</tsoOrigin>
      <actionsSet name="PRA_PST_FR">
        <preventive>true</preventive>
        <curative>false</curative>
        <enforced>false</enforced>
        <action type="PSTTAP">
          <branch order="1" from="FFR2AA1" to="FFR4AA1"/>
          <range>
            <min>-10</min>
            <max>10</max>
          </range>
        </action>
      </actionsSet>
    </complexVariant>
    <complexVariant id="Close line FR1-FR5" name="Close line FR1-FR5">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <tsoOrigin>FR</tsoOrigin>
      <actionsSet name="Close line FR1-FR5">
        <preventive>true</preventive>
        <curative>false</curative>
        <enforced>false</enforced>
        <action type="STATUS">
          <branch from="FFR1AA1" order="1" to="FFR5AA1"/>
          <value>CLOSE</value>
        </action>
      </actionsSet>
    </complexVariant>
    <complexVariant id="Open line FR1-FR2" name="Open line FR1-FR2">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <tsoOrigin>FR</tsoOrigin>
      <actionsSet name="Open line FR1-FR2">
        <preventive>true</preventive>
        <curative>false</curative>
        <enforced>false</enforced>
        <action type="STATUS">
          <branch from="FFR1AA1" order="1" to="FFR2AA1"/>
          <value>OPEN</value>
        </action>
      </actionsSet>
    </complexVariant>
    <complexVariant id="Open line FR1-FR3" name="Open line FR1-FR3">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <tsoOrigin>FR</tsoOrigin>
      <actionsSet name="Open line FR1-FR3">
        <preventive>true</preventive>
        <curative>false</curative>
        <enforced>false</enforced>
        <action type="STATUS">
          <branch from="FFR1AA1" order="1" to="FFR3AA1"/>
          <value>OPEN</value>
        </action>
      </actionsSet>
    </complexVariant>
    <complexVariant id="Open line BE1-BE4" name="Open line BE1-BE4">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <tsoOrigin>BE</tsoOrigin>
      <actionsSet name="Open line BE1-BE4">
        <preventive>true</preventive>
        <curative>false</curative>
        <enforced>false</enforced>
        <action type="STATUS">
          <branch from="BBE1AA1" order="1" to="BBE4AA1"/>
          <value>OPEN</value>
        </action>
      </actionsSet>
    </complexVariant>
    <complexVariant id="Close line DE3-DE4" name="Close line DE3-DE4">
      <timeInterval v="2019-01-07T23:00Z/2019-01-08T23:00Z"/>
      <tsoOrigin>DE</tsoOrigin>
      <actionsSet name="Close line DE3-DE4">
        <preventive>true</preventive>
        <curative>false</curative>
        <enforced>false</enforced>
        <action type="STATUS">
          <branch from="DDE3AA1" order="1" to="DDE4AA1"/>
          <value>CLOSE</value>
        </action>
      </actionsSet>
    </complexVariant>
  </complexVariants>
</FlowBasedConstraintDocument>
